version: 0.1.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
- tools\NuGet\nuget.exe restore src\AgeBaseTemplate.sln
- ps: Install-Product node Stable
- cd src\AgeBaseTemplate.UI
- npm install
- node_modules\.bin\bower -s install
- cd ..\..
build:
  project: src\AgeBaseTemplate.sln
  publish_wap: true
  verbosity: quiet