version: 0.0.{build}
  
configuration: Release

environment:
  db_connection_string:
    secure: G5XvTcAaSK4Ekd1tofzVwUQhr/n7DF1qtaAhbcjKm2NEU4EBgM/cqNdgz0fwMMdhIho0WRhBaw5VPMSVVRcIKghLgWCU9Aj/Wtpz2dgXqIqFzCy4jrOxMtSv2zVfJfbqqWs1DDbPK6Qc4qhlExUUYBi/7bNBrTXQIHxnGXgdLyG1oLeyE4eVymDXqvQRAWVIufMYVTa/CdAW7zbYAL0wm+35xPLxOC12o7nhDYMCYcsQ2sEWlGIspGeS/TsjgU1RdXcx2UsfjJh/3FlPw4UFHot8dNaGuSe1TC8VPopoXUjGHDcHOhfHUT/17/BstWwOvWxcm4Sz44qLlCApOSdk6g==

assembly_info:
  # Version our assemblies
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
  
install:
  # Restore nuget packages
  - cmd: nuget restore -verbosity quiet src\AgeBaseTemplate.sln
  
  # Install latest version of NodeJS
  - ps: Install-Product node Stable
  
  # Install NodeJS and Bower packages
  - cmd: cd src\AgeBaseTemplate.UI
  - cmd: npm --silent install
  - cmd: node_modules\.bin\bower -s install
  - cmd: cd ..\..
  
before_build:
  # Run default gulp task to compile sass and js files
  - cmd: cd src\AgeBaseTemplate.UI
  - cmd: node_modules\.bin\gulp
  - cmd: cd ..\..
  
build:
  # Build solution
  project: src\AgeBaseTemplate.sln
  publish_wap: true
  verbosity: quiet
  
before_deploy:
  # Restore database back to template
  - cmd: tools\RestoreScript\RestoreScript "%db_connection_string%" "src\AgeBaseTemplate.Database\Database.sql"
  
deploy:
  # Use this for continuous deployment
  - provider: Environment
    name: as-agebasetemplate
  
notifications:
  # Notify channel of build
  - provider: Slack
    incoming_webhook: 
      secure: NAeYrmEeVDh5XkM+mloGFWSz3nLL02UTfaDmcytAZH0xytVxI8XHXilaNuGsG1SRAcR5J54LCp8K3twYWyyl6y2nxK5y0Q63zdux+tBBBls=
    channel: '#appveyor'
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: false
